# The URL the site will be built for
base_url = "https://MichaelKutzner.github.io/otcc"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Set theme
theme = "tabi"

# Settings required by tabi
title = "OpenTransportCommunityConference"

default_language = "en"

# Settings for German localization
[languages.de]
build_search_index = true
title = "OpenTransportCommunityConference"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
# highlight_code = true
# highlight_theme = "css"

[extra]
# Put all your custom variables here

# Navigation entries used by tabi
menu = [
    { name = "news", url = "otcc2025", trailing_slash = true },
    { name = "program", url = "program", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
    { name = "contact", url = "contact", trailing_slash = true },
]

# Set favicon
favicon = "images/logo.png"

[translations]
banner_subtitle = "From the community, for the community"
event_date = "October 17 – 18 2025"

[languages.de.translations]
banner_subtitle = "Von der Community, für die Community"
event_date = "17. – 18. Oktober 2025"
